### ISSUE TITLE
New Event and Past Event Bug

### ISSUE THREAD

**Issue by kiwansim** [jumbocodespring2017/bostonathleticsassociation#14]
1. New Event button does not work when the Edit Event window is open
Even if Edit Event window is closed, New Event button still doesn't respond. 
New Event only responds on window reload.

2. Past Event does not click and the window does not show up (check view_past_event in main.js)

**Comment by bmfahey** [comment]
@pulkitjain10 This issue should be fixed when the refactoring is done. Right now, what is happening is that when edit_event or view_past_event make a new event string and put it in the div, it is overwriting your template for New Event, so New Events can never be made again. When the refactoring is done, the HTML shouldn't be overwritten anymore.

**Comment by holeyness** [comment]
@pulkitjain10, here's what i would do, these are just suggestions:

Add both div elements of the new event and the edit event to the right-column block, but turn both not visible at first, and then use js to enable them and disable the other one.
