### ISSUE TITLE
Fix Ionic iterator

### ISSUE THREAD

**Issue by holeyness** [jumbocodespring2017/bostonathleticsassociation#27]
The attendee in attendees ng-repeat doesn't work as desired. Fix it plzz.

Files affected: list.js

**Comment by Philipwzj** [comment]
The ng-repeat part was correct, but localStorage cannot store objects.
Solution: Storing by JSON.stringify(), and JSON.parse, and store it in scope in list.js controller.

**Comment by holeyness** [comment]
Dope, great find. I didn't even think of that.
