### ISSUE TITLE
Investigate and Fix Retrieving Volunteer List on Mobile

### ISSUE THREAD

**Issue by holeyness** [jumbocodespring2017/bostonathleticsassociation#3]
Currently, when you login on the mobile, no volunteers appear to be showing up, even when you successfully configure a volunteer and a team captain on the server side. It could be my mistake, or there could be some issue with retrieving a server side list. 

Please investigate and retrieve the proper list as necessary.

Files of Interest: 
front-end/BAA/www/index.html
front-end/BAA/www/app.js
front-end/BAA/www/list.html
front-end/BAA/www/list.js

**Comment by Philipwzj** [comment]
:)
