### ISSUE TITLE
Update the checkin function

### ISSUE THREAD

**Issue by vivianchen896** [jumbocodespring2017/bostonathleticsassociation#30]
to support three states: in, no show, cancel

files:
list.js

**Comment by Philipwzj** [comment]
@mcmorisi I changed something in the list.html. 
For 
`ng-src="{{(isCheckedIn(attendee) && 'css/checkmark-selected.png' || 'css/checkmark-unselected.png')}}"`
It will show the first image when the function returns true. So, I switched the order of the two images.

And for,
ng-click="changeStatus(attendee, 'checkIn')
I added in one more parameter to see which button is clicked

Thankssss!! ; )

**Comment by Philipwzj** [comment]
@holeyness And for now, the enum for states are: 

StatusEnum = {
    checkedIn : 0,
    noShow : 1,
    cancelled : 2
};
