### ISSUE TITLE
Remove Search on Front End and Load All Events on Load through Django

### ISSUE THREAD

**Issue by holeyness** [jumbocodespring2017/bostonathleticsassociation#4]
The search function is being weird, and it doesn't really line up properly and it doesn't work on firefox.
Remove the search interface, the logic in javascript, and use Django to serve the list of events on load, either adding it to the window variable to operate on with JS or serve it straight up on html.

Files of Interest:
back-end/interface/static/js/main.js
back-end/interface/templates/main.html

**Comment by holeyness** [comment]
@bmfahey  interesting why this didn't actually close the ticket : https://help.github.com/articles/closing-issues-via-commit-messages/.
I guess you can manually close the ticket.

**Comment by bmfahey** [comment]
@holeyness I looked it up, I think maybe it only closes the issue when it gets merged with master? I'll close it manually anyways.
