### ISSUE TITLE
Refactor main.js

### ISSUE THREAD

**Issue by holeyness** [jumbocodespring2017/bostonathleticsassociation#5]
Refactor the main.js such that only logic is there and take all the new_event_string out.
Use javascript to show/hide the overlay, but put the html of the overlay in a static html file

back-end/interface/static/js/main.js

**Comment by ghost** [comment]
Django doesn't update HTML/CSS/JS changes, but when manually added to the elements section of the page, everything works

**Comment by mcmorisi** [comment]
At some point in the near future we will have to get Pulkit merged with the changes that Emily, Brendan, and I have made.

**Comment by ghost** [comment]
Works now thanks Ian you're the bomb
