### ISSUE TITLE
Values for CANCEL/OK are flipped

### ISSUE THREAD

**Issue by holeyness** [jumbocodespring2017/bostonathleticsassociation#75]
If you upload a CSV and have some OK people, if you check it out via the mobile app, the value is flipped, i.e. all the ok people are cancel and vice versa

**Comment by sperrys** [comment]
There was a discrepancy between front-end and back end in terms of what status code meant what, these are now uniform on both sides and the issue is fixed .

0 = NO SHOW
1 = CANCEL 
2 = OK
