### ISSUE TITLE
New Format for CSV

### ISSUE THREAD

**Issue by holeyness** [jumbocodespring2017/bostonathleticsassociation#8]
I was just given a csv file from Mary Miller with updated fields. Basically they keep more data than we were given that one time and we could request the csv to contain specific things if we'd like. Here's the one she sent me.

Please update the code such that it properly parses such a field

ALSO, make sure to write down what format we would like the csv files to be in. (like what fields)

[JumboCode Sample Roster 2-10-17 .xlsx](https://github.com/jumbocodespring2017/bostonathleticsassociation/files/769853/JumboCode.Sample.Roster.2-10-17.xlsx)

Files affected: back-end/api/csv_to_json2.py or whatever file was refactored into.

**Comment by tdoyle01** [comment]
**Fields Needed**

- Firstname
- Lastname
- Email
- JobDescription
- Years of service
- Status vs active (?)
- TeamCaptain
- AssignmentChoiceID
- GeneralEventID vs SpecificEventID (?)

Are team captains their own team captain?
Can we get phone numbers - is new CSV all the fields we are provided?
Is jacket size still a thing?
What is status, and what is active?
How is CSV ordered? in terms of EventListPost

TODO:
Move "status" to Attendee? Equivalent to "at_event"?
Add "AssignmentChoiceID" to Attendee
