### ISSUE TITLE
Add First and Last name to description box

### ISSUE THREAD

**Issue by vivianchen896** [jumbocodespring2017/bostonathleticsassociation#82]
What if there are two Tatis? Tati Doyle Tati Smith? We should have first and last name shown for text box.

<img width="300" alt="screen shot 2017-04-23 at 7 36 16 pm" src="https://cloud.githubusercontent.com/assets/24783112/25318409/26406daa-285c-11e7-8ef1-5a987f04d7e8.png">

**Comment by Philipwzj** [comment]
Byyeeee
