### ISSUE TITLE
Search should filter by first character of name

### ISSUE THREAD

**Issue by vivianchen896** [jumbocodespring2017/bostonathleticsassociation#83]
If I search "o" list of names with O's in them appear. It should only show list of names that begin with an O in the first name or the last name

<img width="308" alt="screen shot 2017-04-23 at 7 39 51 pm" src="https://cloud.githubusercontent.com/assets/24783112/25318432/d35e987c-285c-11e7-9ba6-2076b8b155c1.png">

**Comment by Philipwzj** [comment]
: (
